In [1]:
import pandas as pd

In [ ]:
pip install pandas openpyxl

In [2]:
data=pd.read_csv('WGS.CSV')

In [3]:
data

,#,Name,Company,Value,Tags,Assigned,Status,Source,Last Contact,Created
0,8915,Veeraraghavan Somu,e-commerce_website,NaN,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
1,8916,Naveen,e-commerce_website,NaN,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
2,8917,Nelson,e-commerce_website,NaN,NaN,Jeevitha D,Followup,"web dev |19,999",NaN,02-03-2026 11.09
3,8918,Saravanan Rajendran,e-commerce_website,NaN,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
4,8919,balamurugan chandrasekaran,e-commerce_website,NaN,NaN,Jeevitha D,Followup,"web dev |19,999",NaN,02-03-2026 11.09
...,...,...,...,...,...,...,...,...,...,...
4995,3647,Reshma Menon,Travel Times India P.Ltd,NaN,call back/share proposal,Naresh Naani,call later,FB-DM,19-02-2025 15.32,19-02-2025 15.32
4996,3646,Rajesh Krishnan,Reliable Logistics,NaN,RNR,Sasidharan R,Followup,FB-DM,19-02-2025 15.30,19-02-2025 15.30
4997,3645,karthi,education,NaN,NaN,Sasidharan R,Lost,WhatsApp DM Enquiries,19-02-2025 15.30,19-02-2025 15.30
4998,3644,Sureshkumar,SRSFINCARE,NaN,NaN,Naresh Naani,call later,FB-DM,19-02-2025 15.29,19-02-2025 15.29
4999,3643,Santhosh Kumar,Test 2 build private limited,NaN,send proposal,Naresh Naani,Need to send proposal,FB-DM,19-02-2025 15.27,19-02-2025 15.27

In [4]:
df=pd.DataFrame(data)

In [5]:
df

,#,Name,Company,Value,Tags,Assigned,Status,Source,Last Contact,Created
0,8915,Veeraraghavan Somu,e-commerce_website,NaN,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
1,8916,Naveen,e-commerce_website,NaN,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
2,8917,Nelson,e-commerce_website,NaN,NaN,Jeevitha D,Followup,"web dev |19,999",NaN,02-03-2026 11.09
3,8918,Saravanan Rajendran,e-commerce_website,NaN,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
4,8919,balamurugan chandrasekaran,e-commerce_website,NaN,NaN,Jeevitha D,Followup,"web dev |19,999",NaN,02-03-2026 11.09
...,...,...,...,...,...,...,...,...,...,...
4995,3647,Reshma Menon,Travel Times India P.Ltd,NaN,call back/share proposal,Naresh Naani,call later,FB-DM,19-02-2025 15.32,19-02-2025 15.32
4996,3646,Rajesh Krishnan,Reliable Logistics,NaN,RNR,Sasidharan R,Followup,FB-DM,19-02-2025 15.30,19-02-2025 15.30
4997,3645,karthi,education,NaN,NaN,Sasidharan R,Lost,WhatsApp DM Enquiries,19-02-2025 15.30,19-02-2025 15.30
4998,3644,Sureshkumar,SRSFINCARE,NaN,NaN,Naresh Naani,call later,FB-DM,19-02-2025 15.29,19-02-2025 15.29
4999,3643,Santhosh Kumar,Test 2 build private limited,NaN,send proposal,Naresh Naani,Need to send proposal,FB-DM,19-02-2025 15.27,19-02-2025 15.27

In [6]:
df.drop_duplicates()

,#,Name,Company,Value,Tags,Assigned,Status,Source,Last Contact,Created
0,8915,Veeraraghavan Somu,e-commerce_website,NaN,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
1,8916,Naveen,e-commerce_website,NaN,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
2,8917,Nelson,e-commerce_website,NaN,NaN,Jeevitha D,Followup,"web dev |19,999",NaN,02-03-2026 11.09
3,8918,Saravanan Rajendran,e-commerce_website,NaN,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
4,8919,balamurugan chandrasekaran,e-commerce_website,NaN,NaN,Jeevitha D,Followup,"web dev |19,999",NaN,02-03-2026 11.09
...,...,...,...,...,...,...,...,...,...,...
4995,3647,Reshma Menon,Travel Times India P.Ltd,NaN,call back/share proposal,Naresh Naani,call later,FB-DM,19-02-2025 15.32,19-02-2025 15.32
4996,3646,Rajesh Krishnan,Reliable Logistics,NaN,RNR,Sasidharan R,Followup,FB-DM,19-02-2025 15.30,19-02-2025 15.30
4997,3645,karthi,education,NaN,NaN,Sasidharan R,Lost,WhatsApp DM Enquiries,19-02-2025 15.30,19-02-2025 15.30
4998,3644,Sureshkumar,SRSFINCARE,NaN,NaN,Naresh Naani,call later,FB-DM,19-02-2025 15.29,19-02-2025 15.29
4999,3643,Santhosh Kumar,Test 2 build private limited,NaN,send proposal,Naresh Naani,Need to send proposal,FB-DM,19-02-2025 15.27,19-02-2025 15.27

In [8]:
df.info().df['Value']

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   #             5000 non-null   int64
 1   Name          5000 non-null   str
 2   Company       2790 non-null   str
 3   Value         0 non-null      float64
 4   Tags          1043 non-null   str
 5   Assigned      4975 non-null   str
 6   Status        5000 non-null   str
 7   Source        5000 non-null   str
 8   Last Contact  2720 non-null   str
 9   Created       5000 non-null   str
dtypes: float64(1), int64(1), str(8)
memory usage: 390.8 KB

AttributeError: 'NoneType' object has no attribute 'df'

In [9]:
df=df.drop(columns='Value')

In [10]:
df['Name'].unique()

<StringArray>
[        'Veeraraghavan Somu',                     'Naveen',
                     'Nelson',        'Saravanan Rajendran',
 'balamurugan chandrasekaran',         'Pavithralakshmii_S',
                  'Karthik G',             'Muthu Manickam',
              'Saravanan Sgr',              'Saleem Saleem',
 ...
               'My airtel TN',                     'Ansari',
                 'Dhalavarai',               'சாந்த குமார்',
                     'Sarves',                   'yoganand',
               'Reshma Menon',            'Rajesh Krishnan',
                     'karthi',                'Sureshkumar']
Length: 3949, dtype: str

In [11]:
import re

In [12]:
df['Name']=df['Name'].str.replace(r'[^a-zA-Z]', '', regex=True)

In [13]:
df['Name'] = df['Name'].str.strip()

In [14]:
df['Name'].unique()

<StringArray>
[        'VeeraraghavanSomu',                    'Naveen',
                    'Nelson',        'SaravananRajendran',
 'balamuruganchandrasekaran',         'PavithralakshmiiS',
                  'KarthikG',             'MuthuManickam',
              'SaravananSgr',              'SaleemSaleem',
 ...
         'VikramRavishankar',                'MyairtelTN',
                    'Ansari',                'Dhalavarai',
                    'Sarves',                  'yoganand',
               'ReshmaMenon',            'RajeshKrishnan',
                    'karthi',               'Sureshkumar']
Length: 3878, dtype: str

In [15]:
df['Name']=df['Name'].replace('','unknown names')

In [16]:
df[df['Name'] == "unknown names"].index

Index([  28,   29,   43,  279,  310,  311,  341,  444,  474,  523,
       ...
       4882, 4883, 4886, 4889, 4892, 4896, 4900, 4901, 4907, 4992],
      dtype='int64', length=262)

In [17]:
df['Name']=df['Name'].str.capitalize()

In [18]:
df['Company'].nunique()

2519

In [19]:
df['Company']=df['Company'].str.strip().str.replace(r'[^a-zA-Z]', '', regex=True)

In [20]:
df

,#,Name,Company,Tags,Assigned,Status,Source,Last Contact,Created
0,8915,Veeraraghavansomu,ecommercewebsite,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
1,8916,Naveen,ecommercewebsite,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
2,8917,Nelson,ecommercewebsite,NaN,Jeevitha D,Followup,"web dev |19,999",NaN,02-03-2026 11.09
3,8918,Saravananrajendran,ecommercewebsite,NaN,Jeevitha D,New,"web dev |19,999",NaN,02-03-2026 11.09
4,8919,Balamuruganchandrasekaran,ecommercewebsite,NaN,Jeevitha D,Followup,"web dev |19,999",NaN,02-03-2026 11.09
...,...,...,...,...,...,...,...,...,...
4995,3647,Reshmamenon,TravelTimesIndiaPLtd,call back/share proposal,Naresh Naani,call later,FB-DM,19-02-2025 15.32,19-02-2025 15.32
4996,3646,Rajeshkrishnan,ReliableLogistics,RNR,Sasidharan R,Followup,FB-DM,19-02-2025 15.30,19-02-2025 15.30
4997,3645,Karthi,education,NaN,Sasidharan R,Lost,WhatsApp DM Enquiries,19-02-2025 15.30,19-02-2025 15.30
4998,3644,Sureshkumar,SRSFINCARE,NaN,Naresh Naani,call later,FB-DM,19-02-2025 15.29,19-02-2025 15.29
4999,3643,Santhoshkumar,Testbuildprivatelimited,send proposal,Naresh Naani,Need to send proposal,FB-DM,19-02-2025 15.27,19-02-2025 15.27

In [21]:
df['Company']=df['Company'].str.replace(r'[^a-zA-Z]', '', regex=True)

In [22]:
df['Company']=df['Company'].replace('','unknownCompany')

In [23]:
df['Company']=df['Company'].str.capitalize()

In [24]:
df['Tags']=df['Tags'].str.capitalize()

In [25]:
df['Tags'] = df['Tags'].str.lower().str.strip()

In [26]:
df['Tags'] = df['Tags'].str.replace(r'[^a-z0-9\s]', '', regex=True)

In [27]:
df['Tags'] = df['Tags'].replace({
'rnr': 'not reachable',
'not picking': 'not reachable',
'not answering': 'not reachable',
'switch off': 'switched off',
'switched off': 'switched off',
'ni': 'not interested',
'cb': 'call back',
'cb himself': 'call back',
'proposal send': 'proposal shared'
})

In [28]:
df['Assigned']=df['Assigned'].str.strip()

In [29]:
df['Assigned']=df['Assigned'].str.capitalize()

In [30]:
df['Assigned']=df['Assigned'].fillna('unknown names')

In [31]:
df['Status'].unique()

<StringArray>
[                              'New',                          'Followup',
                        'wrong lead',                    'out of service',
                   'Close Follow up',                         'Wrong Num',
                     'Not answering',                        'call later',
                       'Appointment',                 'Contact Attempted',
                    'Not interested',                      'Switched off',
                     'Not Reachable',                  'Least interested',
            'Not Required @ Present',                'Expected price low',
                 'Appointment Fixed', 'Details has sent through Whatsapp',
                        'On process',              'Closed by other team',
                         'follow-up',                        'Competitor',
                            'Course',                   'Proposal Shared',
                           'Invalid',                         'No-Number',
                   'Looking For Job',                          'Customer',
                  'Already have one',                  'Repeated Contact',
             'looking for candidate',                     'Didnt Enquire',
          'Need to send our profile',                'Ring Not Answering',
                    'Not Responding',                     'Proposal Sent',
                  'Unsucessful Call',                              'busy',
             'Need to send proposal',                    'Other Language',
          'Need to get requirements',  'need to send details in whatsapp',
                              'Lost']
Length: 43, dtype: str

In [32]:
df

,#,Name,Company,Tags,Assigned,Status,Source,Last Contact,Created
0,8915,Veeraraghavansomu,Ecommercewebsite,NaN,Jeevitha d,New,"web dev |19,999",NaN,02-03-2026 11.09
1,8916,Naveen,Ecommercewebsite,NaN,Jeevitha d,New,"web dev |19,999",NaN,02-03-2026 11.09
2,8917,Nelson,Ecommercewebsite,NaN,Jeevitha d,Followup,"web dev |19,999",NaN,02-03-2026 11.09
3,8918,Saravananrajendran,Ecommercewebsite,NaN,Jeevitha d,New,"web dev |19,999",NaN,02-03-2026 11.09
4,8919,Balamuruganchandrasekaran,Ecommercewebsite,NaN,Jeevitha d,Followup,"web dev |19,999",NaN,02-03-2026 11.09
...,...,...,...,...,...,...,...,...,...
4995,3647,Reshmamenon,Traveltimesindiapltd,call backshare proposal,Naresh naani,call later,FB-DM,19-02-2025 15.32,19-02-2025 15.32
4996,3646,Rajeshkrishnan,Reliablelogistics,not reachable,Sasidharan r,Followup,FB-DM,19-02-2025 15.30,19-02-2025 15.30
4997,3645,Karthi,Education,NaN,Sasidharan r,Lost,WhatsApp DM Enquiries,19-02-2025 15.30,19-02-2025 15.30
4998,3644,Sureshkumar,Srsfincare,NaN,Naresh naani,call later,FB-DM,19-02-2025 15.29,19-02-2025 15.29
4999,3643,Santhoshkumar,Testbuildprivatelimited,send proposal,Naresh naani,Need to send proposal,FB-DM,19-02-2025 15.27,19-02-2025 15.27

In [33]:
mapping = {

# Followup
"follow-up":"Followup",

# Not answering group
"Not answering":"Not Answering",
"Ring Not Answering":"Not Answering",
"Not Responding":"Not Answering",
"Unsucessful Call":"Not Answering",

# Wrong number
"Wrong Num":"Wrong Number",
"No-Number":"Wrong Number",

# Switched off
"Switched off":"Switched Off",
"out of service":"Switched Off",

# Proposal
"Proposal Shared":"Proposal Sent",
"Proposal Sent":"Proposal Sent",
"Need to send proposal":"Proposal Pending",

# Requirement
"Need to get requirements":"Followup",

# WhatsApp details
"need to send details in whatsapp":"Followup",

# Profile sending
"Need to send our profile":"Followup",

# Job seekers
"Looking For Job":"Looking For Job",
"looking for candidate":"Looking For Job",

# Lost
"Expected price low":"Lost",
"Competitor":"Lost",

# Invalid leads
"Invalid":"Invalid",
"Didnt Enquire":"Invalid",

# Busy
"busy":"Busy",

# Call later
"call later":"Call Later"
}

In [34]:
df['Status']=df['Status'].replace(mapping)

In [35]:
df['Status']=df['Status'].str.strip()
df['Status']=df['Status'].str.capitalize()

In [36]:
df['Source'].unique()

<StringArray>
[       'web dev |19,999',           'Dm 24,999 Hq',              'ecommerce',
         'Ecommerce Lead',       'WGS Enquiry Form', 'Sathish sir, whats app',
  'WhatsApp DM Enquiries',   'Instagram & Facebook',     'Dm 24,999 free web',
              'dm 24,999',         'Dm24,999-Vivek',        'Mobile App Lead',
            'Direct call',     'Employee Reference',                'Web Dev',
              'dm 29,999',                'App Dev',           'Our Services',
                     'DM',               'DM + App',                  'FB-DM',
            'Andrew lead',               '3 + 1 DM',             '3599 Leads']
Length: 24, dtype: str

In [65]:
mappingSource = {

# Web Development
"web dev |19,999":"Web Development",
"Web Dev":"Web Development",

# Ecommerce
"ecommerce":"Ecommerce",
"Ecommerce Lead":"Ecommerce",

# Mobile App
"Mobile App Lead":"Mobile App Development",
"App Dev":"Mobile App Development",

# Social Media DM
"DM":"Social Media DM",
"dm 24,999":"Social Media DM",
"Dm 24,999 Hq":"Social Media DM",
"Dm24,999-Vivek":"Social Media DM",
"DM + App":"Social Media DM",
"FB-DM":"Social Media DM",
"Instagram & Facebook":"Social Media DM",

"Dm 24,999 free web":"Social Media DM",
"Dm 29,999":"Social Media DM",

# WhatsApp
"WhatsApp DM Enquiries":"WhatsApp",
"Sathish sir, whats app":"WhatsApp",

# Website Form
"WGS Enquiry Form":"Website Form",

# Direct
"Direct call":"Direct Call",

# Employee
"Employee Reference":"Employee Reference",

# Campaign
"Andrew lead":"Campaign Lead",
"3 + 1 DM":"Campaign Lead",
"3599 Leads":"Campaign Lead"
}

In [66]:
df['Source']=df['Source'].replace(mappingSource)
df['Source']=df['Source'].str.strip()
df['Source']=df['Source'].str.capitalize()

In [39]:
df['Last Contact'].unique()

<StringArray>
[               nan, '02-03-2026 13.00', '27-02-2026 10.58',
 '16-02-2026 19.04', '16-02-2026 19.02', '16-02-2026 19.01',
 '11-02-2026 12.00', '10-02-2026 18.00', '10-02-2026 13.29',
 '09-02-2026 14.22',
 ...
 '19-02-2025 15.49', '19-02-2025 15.48', '19-02-2025 15.45',
 '19-02-2025 15.39', '19-02-2025 15.37', '19-02-2025 15.35',
 '19-02-2025 15.32', '19-02-2025 15.30', '19-02-2025 15.29',
 '19-02-2025 15.27']
Length: 2451, dtype: str

In [40]:
df["Last Contact"] = df["Last Contact"].str.replace(".", ":", regex=False)

In [41]:
df["Last Contact"] = pd.to_datetime(df["Last Contact"], format="%d-%m-%Y %H:%M", errors="coerce")

In [42]:
df

,#,Name,Company,Tags,Assigned,Status,Source,Last Contact,Created
0,8915,Veeraraghavansomu,Ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,02-03-2026 11.09
1,8916,Naveen,Ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,02-03-2026 11.09
2,8917,Nelson,Ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,02-03-2026 11.09
3,8918,Saravananrajendran,Ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,02-03-2026 11.09
4,8919,Balamuruganchandrasekaran,Ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,02-03-2026 11.09
...,...,...,...,...,...,...,...,...,...
4995,3647,Reshmamenon,Traveltimesindiapltd,call backshare proposal,Naresh naani,Call later,Social media dm,2025-02-19 15:32:00,19-02-2025 15.32
4996,3646,Rajeshkrishnan,Reliablelogistics,not reachable,Sasidharan r,Followup,Social media dm,2025-02-19 15:30:00,19-02-2025 15.30
4997,3645,Karthi,Education,NaN,Sasidharan r,Lost,Whatsapp,2025-02-19 15:30:00,19-02-2025 15.30
4998,3644,Sureshkumar,Srsfincare,NaN,Naresh naani,Call later,Social media dm,2025-02-19 15:29:00,19-02-2025 15.29
4999,3643,Santhoshkumar,Testbuildprivatelimited,send proposal,Naresh naani,Proposal pending,Social media dm,2025-02-19 15:27:00,19-02-2025 15.27

In [43]:
df["Contact Year"] = df["Last Contact"].dt.year
df["Contact Month"] = df["Last Contact"].dt.month
df["Contact Day"] = df["Last Contact"].dt.day
df["Contact Hour"] = df["Last Contact"].dt.time

In [44]:
df

,#,Name,Company,Tags,Assigned,Status,Source,Last Contact,Created,Contact Year,Contact Month,Contact Day,Contact Hour
0,8915,Veeraraghavansomu,Ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,02-03-2026 11.09,NaN,NaN,NaN,NaT
1,8916,Naveen,Ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,02-03-2026 11.09,NaN,NaN,NaN,NaT
2,8917,Nelson,Ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,02-03-2026 11.09,NaN,NaN,NaN,NaT
3,8918,Saravananrajendran,Ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,02-03-2026 11.09,NaN,NaN,NaN,NaT
4,8919,Balamuruganchandrasekaran,Ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,02-03-2026 11.09,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,3647,Reshmamenon,Traveltimesindiapltd,call backshare proposal,Naresh naani,Call later,Social media dm,2025-02-19 15:32:00,19-02-2025 15.32,2025.0,2.0,19.0,15:32:00
4996,3646,Rajeshkrishnan,Reliablelogistics,not reachable,Sasidharan r,Followup,Social media dm,2025-02-19 15:30:00,19-02-2025 15.30,2025.0,2.0,19.0,15:30:00
4997,3645,Karthi,Education,NaN,Sasidharan r,Lost,Whatsapp,2025-02-19 15:30:00,19-02-2025 15.30,2025.0,2.0,19.0,15:30:00
4998,3644,Sureshkumar,Srsfincare,NaN,Naresh naani,Call later,Social media dm,2025-02-19 15:29:00,19-02-2025 15.29,2025.0,2.0,19.0,15:29:00
4999,3643,Santhoshkumar,Testbuildprivatelimited,send proposal,Naresh naani,Proposal pending,Social media dm,2025-02-19 15:27:00,19-02-2025 15.27,2025.0,2.0,19.0,15:27:00

In [45]:
df['Created']=df['Created'].str.replace(".", ":", regex=False)

In [46]:
df["Created"] = pd.to_datetime(df["Created"], format="%d-%m-%Y %H:%M", errors="coerce")

In [47]:
df["Created Year"] = df["Created"].dt.year
df["Created Month"] = df["Created"].dt.month
df["Created Day"] = df["Created"].dt.day
df["Created Hour"] = df["Created"].dt.time

df["Created Quarter"] = "Q"+ df["Created"].dt.quarter.astype(str)

In [48]:
df = df.rename(columns={"#": "ID"})

In [49]:
df

,ID,Name,Company,Tags,Assigned,Status,Source,Last Contact,Created,Contact Year,Contact Month,Contact Day,Contact Hour,Created Year,Created Month,Created Day,Created Hour,Created Quarter
0,8915,Veeraraghavansomu,Ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
1,8916,Naveen,Ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
2,8917,Nelson,Ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
3,8918,Saravananrajendran,Ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
4,8919,Balamuruganchandrasekaran,Ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,3647,Reshmamenon,Traveltimesindiapltd,call backshare proposal,Naresh naani,Call later,Social media dm,2025-02-19 15:32:00,2025-02-19 15:32:00,2025.0,2.0,19.0,15:32:00,2025,2,19,15:32:00,Q1
4996,3646,Rajeshkrishnan,Reliablelogistics,not reachable,Sasidharan r,Followup,Social media dm,2025-02-19 15:30:00,2025-02-19 15:30:00,2025.0,2.0,19.0,15:30:00,2025,2,19,15:30:00,Q1
4997,3645,Karthi,Education,NaN,Sasidharan r,Lost,Whatsapp,2025-02-19 15:30:00,2025-02-19 15:30:00,2025.0,2.0,19.0,15:30:00,2025,2,19,15:30:00,Q1
4998,3644,Sureshkumar,Srsfincare,NaN,Naresh naani,Call later,Social media dm,2025-02-19 15:29:00,2025-02-19 15:29:00,2025.0,2.0,19.0,15:29:00,2025,2,19,15:29:00,Q1
4999,3643,Santhoshkumar,Testbuildprivatelimited,send proposal,Naresh naani,Proposal pending,Social media dm,2025-02-19 15:27:00,2025-02-19 15:27:00,2025.0,2.0,19.0,15:27:00,2025,2,19,15:27:00,Q1

In [50]:
df = df[~df['Company'].str.contains(r'\d{10}', na=False)]

In [52]:
df['Company'] = df['Company'].replace({
    'self employed':'Self-Employed',
    'own business':'Self-Employed',
    'entreprenur':'Entrepreneur',
    'not yet working':'Student'
})

In [53]:
df['Company'] = df['Company'].str.strip()
df['Company'] = df['Company'].str.lower()

In [54]:
df

,ID,Name,Company,Tags,Assigned,Status,Source,Last Contact,Created,Contact Year,Contact Month,Contact Day,Contact Hour,Created Year,Created Month,Created Day,Created Hour,Created Quarter
0,8915,Veeraraghavansomu,ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
1,8916,Naveen,ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
2,8917,Nelson,ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
3,8918,Saravananrajendran,ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
4,8919,Balamuruganchandrasekaran,ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,3647,Reshmamenon,traveltimesindiapltd,call backshare proposal,Naresh naani,Call later,Social media dm,2025-02-19 15:32:00,2025-02-19 15:32:00,2025.0,2.0,19.0,15:32:00,2025,2,19,15:32:00,Q1
4996,3646,Rajeshkrishnan,reliablelogistics,not reachable,Sasidharan r,Followup,Social media dm,2025-02-19 15:30:00,2025-02-19 15:30:00,2025.0,2.0,19.0,15:30:00,2025,2,19,15:30:00,Q1
4997,3645,Karthi,education,NaN,Sasidharan r,Lost,Whatsapp,2025-02-19 15:30:00,2025-02-19 15:30:00,2025.0,2.0,19.0,15:30:00,2025,2,19,15:30:00,Q1
4998,3644,Sureshkumar,srsfincare,NaN,Naresh naani,Call later,Social media dm,2025-02-19 15:29:00,2025-02-19 15:29:00,2025.0,2.0,19.0,15:29:00,2025,2,19,15:29:00,Q1
4999,3643,Santhoshkumar,testbuildprivatelimited,send proposal,Naresh naani,Proposal pending,Social media dm,2025-02-19 15:27:00,2025-02-19 15:27:00,2025.0,2.0,19.0,15:27:00,2025,2,19,15:27:00,Q1

In [59]:
df['Last Contact'].unique()

<DatetimeArray>
[                'NaT', '2026-03-02 13:00:00', '2026-02-27 10:58:00',
 '2026-02-16 19:04:00', '2026-02-16 19:02:00', '2026-02-16 19:01:00',
 '2026-02-11 12:00:00', '2026-02-10 18:00:00', '2026-02-10 13:29:00',
 '2026-02-09 14:22:00',
 ...
 '2025-02-19 15:49:00', '2025-02-19 15:48:00', '2025-02-19 15:45:00',
 '2025-02-19 15:39:00', '2025-02-19 15:37:00', '2025-02-19 15:35:00',
 '2025-02-19 15:32:00', '2025-02-19 15:30:00', '2025-02-19 15:29:00',
 '2025-02-19 15:27:00']
Length: 2451, dtype: datetime64[us]

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               5000 non-null   int64
 1   Name             5000 non-null   str
 2   Company          2790 non-null   str
 3   Tags             1043 non-null   str
 4   Assigned         5000 non-null   str
 5   Status           5000 non-null   str
 6   Source           5000 non-null   str
 7   Last Contact     2720 non-null   datetime64[us]
 8   Created          5000 non-null   datetime64[us]
 9   Contact Year     2720 non-null   float64
 10  Contact Month    2720 non-null   float64
 11  Contact Day      2720 non-null   float64
 12  Contact Hour     2720 non-null   object
 13  Created Year     5000 non-null   int32
 14  Created Month    5000 non-null   int32
 15  Created Day      5000 non-null   int32
 16  Created Hour     5000 non-null   object
 17  Created Quarter  5000 non-null   str
dtypes: datetime64[us](2), float64(3), int32(3), int64(1), object(2), str(7)
memory usage: 644.7+ KB

In [62]:
df = df[df['Company'] != ""]

In [63]:
df = df[df['Tags'] != ""]
df = df[df['Company'] != ""]
df = df[df['Last Contact'] != ""]

In [64]:
df

,ID,Name,Company,Tags,Assigned,Status,Source,Last Contact,Created,Contact Year,Contact Month,Contact Day,Contact Hour,Created Year,Created Month,Created Day,Created Hour,Created Quarter
0,8915,Veeraraghavansomu,ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
1,8916,Naveen,ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
2,8917,Nelson,ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
3,8918,Saravananrajendran,ecommercewebsite,NaN,Jeevitha d,New,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
4,8919,Balamuruganchandrasekaran,ecommercewebsite,NaN,Jeevitha d,Followup,Web development,NaT,2026-03-02 11:09:00,NaN,NaN,NaN,NaT,2026,3,2,11:09:00,Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,3647,Reshmamenon,traveltimesindiapltd,call backshare proposal,Naresh naani,Call later,Social media dm,2025-02-19 15:32:00,2025-02-19 15:32:00,2025.0,2.0,19.0,15:32:00,2025,2,19,15:32:00,Q1
4996,3646,Rajeshkrishnan,reliablelogistics,not reachable,Sasidharan r,Followup,Social media dm,2025-02-19 15:30:00,2025-02-19 15:30:00,2025.0,2.0,19.0,15:30:00,2025,2,19,15:30:00,Q1
4997,3645,Karthi,education,NaN,Sasidharan r,Lost,Whatsapp,2025-02-19 15:30:00,2025-02-19 15:30:00,2025.0,2.0,19.0,15:30:00,2025,2,19,15:30:00,Q1
4998,3644,Sureshkumar,srsfincare,NaN,Naresh naani,Call later,Social media dm,2025-02-19 15:29:00,2025-02-19 15:29:00,2025.0,2.0,19.0,15:29:00,2025,2,19,15:29:00,Q1
4999,3643,Santhoshkumar,testbuildprivatelimited,send proposal,Naresh naani,Proposal pending,Social media dm,2025-02-19 15:27:00,2025-02-19 15:27:00,2025.0,2.0,19.0,15:27:00,2025,2,19,15:27:00,Q1

In [67]:
df.to_csv('clean1.csv',index=False)